spring:
  # Development Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/zyra_travel_dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Enable H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console

# Development Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: always

# Development Logging Configuration
logging:
  level:
    root: INFO
    com.zyra: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development-specific settings
app:
  security:
    require-ssl: false
  
  email:
    enabled: false
    smtp-host: localhost
    smtp-port: 1025  # MailHog default port

  # Feature flags for development
  features:
    enable-swagger: true
    enable-actuator: true
    enable-dev-endpoints: true