spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Zyra
    username: postgres
    password: Mininiru
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Just validate the schema, don't create or update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # Disable OSIV pattern
  sql:
    init:
      mode: never  # Disable automatic schema initialization
  flyway:
    enabled: false  # Keep Flyway disabled since we're not using it
  main:
    allow-bean-definition-overriding: true
  cache:
    type: none  # Disable caching by default

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG
    com.zyra: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration
app:
  jwt:
    secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897894b8be5f7c6b4e44f0f1f78
    expiration: 86400000  # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  max-age: 3600 