spring:
  application:
    name: zyra-travel-service
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_agency
    username: postgres
    password: yourpassword
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

security:
  jwt:
    secret: ${JWT_SECRET:your-default-secret-key-minimum-256-bits}
    expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.zyra: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

app:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    max-age: 3600
  
  pagination:
    default-page-size: 20
    max-page-size: 100