spring:
  # Production Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Zyra}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

# Production Server Configuration
server:
  error:
    include-stacktrace: never
  tomcat:
    max-threads: 200
    min-spare-threads: 20

# Production Logging Configuration
logging:
  level:
    root: WARN
    com.zyra: INFO
    org.hibernate: WARN
  file:
    name: /var/log/zyra-travel/application.log
    max-size: 10MB
    max-history: 30

# Production-specific settings
app:
  security:
    require-ssl: true
  email:
    enabled: false  # Disable email functionality

# Feature flags for production
features:
  enable-swagger: false
  enable-actuator: true
  enable-dev-endpoints: false

# CDN Configuration
cdn:
  enabled: true
  base-url: ${CDN_BASE_URL}

# Production Cache Configuration
cache:
  type: none  # No caching 