spring:
  # Production Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:zyra_travel}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  # Production Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

# Production Server Configuration
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100

# Production Logging Configuration
logging:
  level:
    root: WARN
    com.zyra: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/zyra-travel/application.log
    max-size: 10MB
    max-history: 30

# Production-specific settings
app:
  security:
    require-ssl: true
    rate-limit:
      enabled: true
      max-requests: 100
      time-window: 60 # seconds
  
  email:
    enabled: true
    smtp-host: ${SMTP_HOST}
    smtp-port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    from-address: no-reply@zyra-travel.com

  # Feature flags for production
  features:
    enable-swagger: false
    enable-actuator: true
    enable-dev-endpoints: false

  # CDN Configuration
  cdn:
    enabled: true
    base-url: ${CDN_BASE_URL} 